{% set name = "watchexec" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/watchexec/watchexec/archive/v{{ version }}.tar.gz
  sha256: 8d8e3c1de05daae24a31ea59d61631812b6044a74231aaa0e5a2ee15203898e8

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - watchexec --help

about:
  home: https://github.com/watchexec/watchexec
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Execute commands when watched files change
  dev_url: https://github.com/watchexec/watchexec

extra:
  recipe-maintainers:
    - danielnachun
