context:
  version: "2.4.3"

package:
  name: watchexec
  version: ${{ version }}

source:
  url: https://github.com/watchexec/watchexec/archive/v${{ version }}.tar.gz
  sha256: 080b6ef6d1c5b030def96ac8c4e4d3fec85091b320088144d345331d3e51eeec

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - watchexec --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Execute commands when watched files change
  homepage: https://github.com/watchexec/watchexec
  repository: https://github.com/watchexec/watchexec

extra:
  recipe-maintainers:
    - danielnachun
