context:
  version: "2.5.0"

package:
  name: watchexec
  version: ${{ version }}

source:
  url: https://github.com/watchexec/watchexec/archive/v${{ version }}.tar.gz
  sha256: c03e5060f832069f3e32e61e8fb3600e6b9c18fc68829176d5fcfd53a86481a8

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - watchexec --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Execute commands when watched files change
  homepage: https://github.com/watchexec/watchexec
  repository: https://github.com/watchexec/watchexec

extra:
  recipe-maintainers:
    - danielnachun
